/**
 * Centralized DOM references used by main.js.
 * Keeping selectors in one file reduces merge conflicts for UI-related tasks.
 */

const languageOptions = document.getElementById('language-options');

export const dom = {
    inputArea: document.getElementById('input-area'),
    fileInput: document.getElementById('file-input'),
    pickFileBtn: document.getElementById('pick-file-btn'),
    fileInfoBar: document.getElementById('file-info-bar'),
    selectedFileName: document.getElementById('selected-file-name'),
    removeFileBtn: document.getElementById('remove-file-btn'),
    languageSelectTrigger: document.getElementById('language-select-trigger'),
    languageSelectLabel: document.getElementById('language-select-label'),
    languageOptions,
    languageItems: languageOptions.querySelectorAll('.dropdown-item'),
    startBtn: document.getElementById('start-btn'),
    progressArea: document.getElementById('progress-area'),
    resultArea: document.getElementById('result-area'),
    statusText: document.getElementById('status-text'),
    timerDisplay: document.getElementById('timer'),
    transcriptPreview: document.getElementById('transcript-preview'),
    downloadMdBtn: document.getElementById('download-md'),
    copyTranscriptBtn: document.getElementById('copy-transcript'),
    newUploadBtn: document.getElementById('new-upload-btn'),
    resultMeta: document.getElementById('result-meta'),
    errorMessage: document.getElementById('error-message'),
    uploadStatusLine: document.getElementById('upload-status-line'),
    transcribeStatusLine: document.getElementById('transcribe-status-line'),
    uploadProgressFill: document.getElementById('upload-progress-fill'),
    transcribeProgressFill: document.getElementById('transcribe-progress-fill'),
    recordBtn: document.getElementById('record-btn'),
    recordStatus: document.getElementById('record-status'),
    volumeMeter: document.getElementById('volume-meter'),
    waveBars: document.querySelectorAll('.wave-bar'),
    recordPlayback: document.getElementById('record-playback'),
    resultPlayback: document.getElementById('result-playback'),
    uploadSection: document.getElementById('upload-section'),
    recordSection: document.getElementById('record-section'),
    recordInfoBar: document.getElementById('record-info-bar'),
    removeRecordBtn: document.getElementById('remove-record-btn'),
    quotaDisplay: document.getElementById('quota-display'),
    quotaText: document.getElementById('quota-text'),

    cpPlayerUI: document.getElementById('record-playback-ui'),
    cpPlayBtn: document.getElementById('cp-play-btn'),
    cpIconPlay: document.getElementById('cp-icon-play'),
    cpIconPause: document.getElementById('cp-icon-pause'),
    cpCurrentTime: document.getElementById('cp-current'),
    cpDurationTime: document.getElementById('cp-duration'),
    cpSpeedBtn: document.getElementById('cp-speed-btn'),
    cpTrack: document.getElementById('cp-track'),
    cpFill: document.getElementById('cp-fill'),
    cpThumb: document.getElementById('cp-thumb'),
    cpDownloadBtn: document.getElementById('cp-download-btn'),

    resPlayerUI: document.getElementById('result-playback-ui'),
    resPlayBtn: document.getElementById('res-play-btn'),
    resIconPlay: document.getElementById('res-icon-play'),
    resIconPause: document.getElementById('res-icon-pause'),
    resCurrentTime: document.getElementById('res-current'),
    resDurationTime: document.getElementById('res-duration'),
    resSpeedBtn: document.getElementById('res-speed-btn'),
    resTrack: document.getElementById('res-track'),
    resFill: document.getElementById('res-fill'),
    resThumb: document.getElementById('res-thumb'),
    resDownloadBtn: document.getElementById('res-download-btn'),

    confirmModal: document.getElementById('confirm-modal'),
    confirmOkBtn: document.getElementById('confirm-ok'),
    confirmCancelBtn: document.getElementById('confirm-cancel'),
    modalTitle: document.getElementById('modal-title'),

    historyList: document.getElementById('history-list'),
    historyClearBtn: document.getElementById('history-clear-btn'),
    historyEmpty: document.getElementById('history-empty'),

    appLangTrigger: document.getElementById('app-lang-trigger'),
    appLangLabel: document.getElementById('app-lang-label'),
    appLangOptions: document.getElementById('app-lang-options'),
    recordLabel: document.getElementById('record-label'),
    recordSvgMic: document.getElementById('record-svg-mic'),
    recordSvgStop: document.getElementById('record-svg-stop'),
    actionWrapper: document.getElementById('action-wrapper'),
    historyPanel: document.getElementById('history-panel'),

    // Real-time Transcription Elements
    realtimeToggleInput: document.getElementById('realtime-toggle-input'),
    realtimePanel: document.getElementById('realtime-panel-result'),
    realtimeChunksContainer: document.getElementById('realtime-chunks-container-result'),
    recordingSidebar: document.getElementById('recording-sidebar'),
    resultsSidebar: document.getElementById('results-sidebar'),
    transcriptPreviewBox: document.getElementById('transcript-preview-box'),

    // AI Meeting Minutes Elements
    resultTabs: document.getElementById('result-tabs'),
    tabTranscript: document.getElementById('tab-transcript'),
    tabMinutes: document.getElementById('tab-minutes'),
    tabMinutesStatus: document.getElementById('tab-minutes-status'),
    minutesPreviewBox: document.getElementById('minutes-preview-box'),
    minutesLoading: document.getElementById('minutes-loading'),
    minutesErrorView: document.getElementById('minutes-error-view'),
    retryMinutesBtn: document.getElementById('retry-minutes-btn'),
    minutesPreview: document.getElementById('minutes-preview'),
};
